### ISSUE TITLE
Context::find_location doesn't work in combination with ASLR on macOS

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/addr2line#114]

**Comment by philipc** [comment]
ASLR is a general problem for gimli (eg https://github.com/xd009642/tarpaulin needs a fix for this too), and it came up recently in https://github.com/jonhoo/inferno/issues/31 as well, which says that `nperf` has fixed it, would be good to see if we can come up with a general solution that everyone can use.

**Comment by bjorn3** [comment]
I currently workaround it using `RUSTFLAGS="-Clink-args=-Wl,-no_pie"` which makes ASLR impossible.

**Comment by main--** [comment]
You are generally supposed to de-ASLR the addresses yourself before putting them into addr2line (a simple and unavoidable fact, not much we can do about it). Consider using the `findshlibs` crate (or something similar) in order to find where your binary is mapped in memory, then subtract the offset.

**Comment by philipc** [comment]
Ah yeah, so there's two cases: same process or other process. If same process (such as when doing backtraces) then `findshlibs` works, but I don't see how to do that for other processes. That's where things like `nperf`'s solution come in.

**Comment by bjorn3** [comment]
Will try `findshlibs`. I am working on nicer backtraces. (syntax highlighted source and call args showing in the future)

**Comment by bjorn3** [comment]
`findshlibs` works perfect.
