### ISSUE TITLE
"Invalid ELF section header offset/size/alignment" panic

### ISSUE THREAD

**Issue by slonopotamus** [gimli-rs/addr2line#170]
1. Download zip archive with problematic elf file: [1.elf.zip](https://github.com/gimli-rs/addr2line/files/4644952/1.elf.zip)
2. Unpack it somewhere
3. Using addr2line `master` branch, run `cargo run --example=addr2line -- -e /path/to/1.elf 0x80`

Expected output (as produced by addr2line from GNU binutils):
```Z:\/1.c:1```
I'm not sure why there are two slashes, but path and line number are correct.

Actual output:
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("Invalid ELF section header offset/size/alignment")', examples\addr2line.rs:156:17```

**Comment by philipc** [comment]
Thanks for the report. This is an issue with the [object](https://github.com/gimli-rs/object) crate though.

Looking at the file, the section headers are incorrectly aligned (4 bytes instead of 8 bytes), but maybe this is common enough that we have to handle it anyway. Which linker was used to create this file?

**Comment by slonopotamus** [comment]
This binary was created with PS4 toolchain.
