### ISSUE TITLE
addr2line is slower than the binutils version

### ISSUE THREAD

**Issue by philipc** [gimli-rs/addr2line#2]
From https://github.com/gimli-rs/gimli/issues/53.

One probable optimization will be to cache the parsed `.debug_line` rows.

**Comment by jonhoo** [comment]
Another I'm looking into right now is to use a `BTreeMap` indexed by base address to keep the `Unit`s in. By then looking into the range `(-, addr]` and stepping backwards through the iterator, we should be much more efficient about doing the lookups.

**Comment by jonhoo** [comment]
One thing that would speed things up significantly is if we had a way to binary search the line rows within a particular `Unit`. Currently, we scan left to right and stop when the next entry is larger than the address we're looking for, but if we could efficiently skip backwards and forwards (like in an array), this would be much faster. @fitzgen, is there a way to make the `StateMachine` that's returned by `gimli::LineNumberProgramHeader::rows()` allow efficient seeking, not just one-at-a-time processing?

**Comment by fitzgen** [comment]
> @fitzgen, is there a way to make the StateMachine that's returned by gimli::LineNumberProgramHeader::rows() allow efficient seeking, not just one-at-a-time processing?

I don't think so. The address, line number, source file, etc matrix is encoded and compressed into a bytecode program, and `StateMachine` is interpreting that program to yield one row of the matrix at a time. Each row of the matrix requires information from the previous one, since (per spec) all the bytecodes mutate the current row being reconstructed in place, and often deal with relative numbers and deltas rather than absolute numbers, since they can be used to encode the matrix more compactly.

**Comment by fitzgen** [comment]
Also, FWIW, it isn't clear that we are still really slower than the canonical binutils `addr2line`. We would certainly benefit from more benchmarking.

**Comment by jonhoo** [comment]
And from profiling, most of the time seems to be spent in iterating over `rows()`. It's unfortunate we can't skip through it.. I don't really want to extract them all at start-up time, as that would waste significant memory, plus slow down applications that *don't* do a lot of lookups. Maybe a simple addr->file cache is sufficient.

**Comment by fitzgen** [comment]
Thanks for doing additional profiling!

**Comment by jonhoo** [comment]
One further thought on optimizing the walking of line rows: what if, when we walk it, we keep track of a couple of byte offset + address tuples at fixed intervals along the way. That way, the next time we walk, we can binary search those recorded points, and only do a linear scan from the last point before the address we're looking for. If an address ends up having to walk beyond the last recorded point, it records more points as it walks. The interval could be tuned such that the number of stored points is relatively small, and this would still provide a massive (probably order of magnitude) decrease in runtime. Thoughts @philipc @fitzgen ?

**Comment by fitzgen** [comment]
I think we could perhaps clone the line number `StateMachine` periodically, to bound the amount of recomputation we need to do.

We can't jump into the middle of a line program because there is implicit state built up and referenced in later instructions. However, cloning the `StateMachine` should work, as long as we don't share headers between clones, as those get mutated by some line number instructions.

Caching *all* line rows is overkill and I don't think it is the approach to take. There's a *lot* of rows and the vast majority of them won't be reused, meaning we are wasting time and space by cloning and caching all of them.

**Comment by jonhoo** [comment]
Yeah, of course, I was still imagining that we only cache every `n`th row. But this still enables doing a binary search to get most of the way to the address in question, which should improve performance drastically. How expensive is `StateMachine` to clone? We'd need to pick a reasonable `n`. Also, should we do this eagerly (when the `Mapping` is created), upon request (when the user calls `optimize()`), or lazily (as we traverse)? If we do it lazily, should it be optional?

**Comment by fitzgen** [comment]
> But this still enables doing a binary search to get most of the way to the address in question, which should improve performance drastically.

And if you are only saving every nth row, we'll still need to be able to continue evaluation of the line number program from the closest preceding row snapshot'd when we don't have an exact match in the binary search. The state required to continue evaluation is exactly `StateMachine`, so I think we are reaching consensus.

> How expensive is StateMachine to clone?

Well, we don't actually even derive `Clone` on it yet, but just because we haven't needed it, not because there is anything that is fundamentally un-`Clone`-able.

So I guess the answer is "measure and we'll find out" ? :)

> We'd need to pick a reasonable n.

Ideally we would do something like `sqrt(n)` where `n` is number of rows in the program. The `sqrt` is non-constant so we actually get a big-O improvement, not just a constant shave. Super important ;)

However, we don't know the number of rows in the program (or even the number of instructions) until we run it (or parse, for instructions).

I think it would be fine if we looked at the average number of bytes per row in line number programs in the wild, and use that number in `addr2line` to estimate what `n` is in the given unparsed line number program, and clone the `StateMachine` every `sqrt(estimate(n))` rows.

Or maybe this is over-engineering and we can just do every 100 rows or something :P

> Also, should we do this eagerly (when the Mapping is created), upon request (when the user calls optimize()), or lazily (as we traverse)? If we do it lazily, should it be optional?

I would say lazily and if we do it optionally (I don't have a strong opinion) then it is time to make a builder struct for all the options to keep them sane and not have tons of bool parameters for every function.

**Comment by philipc** [comment]
> Caching all line rows is overkill and I don't think it is the approach to take.

I think it's always good to look at what existing DWARF implementations do. That doesn't mean we need to copy what they do, but if it's code that's in production use then it's a good baseline.

The elfutils addr2line parses all of the line number information for a CU into an array (which it caches), and then does a binary search in that array for each address.

I didn't completely read what gdb does. It seems to parse and cache all the line number information, but it also splits up the rows into one array per file.

> How expensive is StateMachine to clone?

It's not particularly cheap, because it does include the `LineNumberProgramHeader`, which in turn includes vectors of files and directories.

My feeling is that we should start by caching every line row. This should be fast to implement and gives a baseline. We can then investigate ways to improve that further (including to reduce memory usage), such as the other methods suggested here.

**Comment by philipc** [comment]
Another possibility is to cache the starting offset and address range of each sequence. This is because the `DW_LNE_end_sequence` opcode resets the state machine, so we wouldn't need to save the full state. So then you could binary search for the sequence, and evaluate from there.

**Comment by jonhoo** [comment]
@fitzgen That seems pretty reasonable. I think we should start with just a fixed `n`, and then make it dynamic after evaluating if it actually helps.

@philipc It's interesting that `addr2line` actually does a binary search -- their performance doesn't suggest that that's the case. When you say "cache every row", what information are you intending to cache? `(addr, file-ptr, lineno)`? That's potentially a lot of extra state to create, and it is certainly a significant step away from the `gimli` zero-copy starting point. Keeping the *full* information for every `n`'th row seems like it wouldn't actually help, since you then don't have a way of looking up the rows in between. Re: keeping byte offsets, this was basically my earlier suggestion in https://github.com/gimli-rs/addr2line/issues/2#issuecomment-265206815 of caching `(address, byte offset)` every `n` lines, and then start a new `StateMachine` from the offset closest by binary search. But from @fitzgen's comments, it seemed like there isn't a way to start the `StateMachine` at some arbitrary (but valid) byte offset?

**Comment by fitzgen** [comment]
> Another possibility is to cache the starting offset and address range of each sequence. This is because the DW_LNE_end_sequence opcode resets the state machine, so we wouldn't need to save the full state. So then you could binary search for the sequence, and evaluate from there.

The one catch is that it doesn't reset the defined files. We might be able to special case, though.

**Comment by fitzgen** [comment]
@philipc thanks (as always) for digging into other code bases :)

**Comment by philipc** [comment]
> It's interesting that addr2line actually does a binary search -- their performance doesn't suggest that that's the case. 

That may be because I looked at the wrong addr2line :) I'll look at binutils addr2line later today.

> When you say "cache every row", what information are you intending to cache? (addr, file-ptr, lineno)? That's potentially a lot of extra state to create, and it is certainly a significant step away from the gimli zero-copy starting point. 

Basically that, but you may also need an end-sequence flag to handle gaps. Agree that it is a lot to cache, but whether that is a problem depends on whether your goal is high performance or low memory usage. I don't think it'll be significantly worse than caching every 100th state machine, but that is something to measure. zero-copy is a more relevant goal for the low level code. Avoiding unnecessary copies is always good, but avoiding all copies is not always the correct tradeoff. Making the low level parsing avoid copies does let you move that tradeoff decision to the higher level code though.

> it seemed like there isn't a way to start the StateMachine at some arbitrary (but valid) byte offset

In general there isn't, but we could add support for restarting after `DW_LNE_end_sequence` opcodes.

> The one catch is that it doesn't reset the defined files. We might be able to special case, though.

Yep. I think it is feasible to special case that, but it'll be a bit ugly.

**Comment by fitzgen** [comment]
> Yep. I think it is feasible to special case that, but it'll be a bit ugly.

FWIW, I think we should investigate `Clone`ing before special casing. it might be that it isn't really a problem in practice, despite cloning `Vec`s. I suspect that the `Vec`s are not very large since each compilation unit ends up with its own line number program in practice, IIRC.

**Comment by jonhoo** [comment]
Once we have `Clone` I can take a quick stab at coding this up.

**Comment by fitzgen** [comment]
> Once we have Clone I can take a quick stab at coding this up.

Derived clone in https://github.com/gimli-rs/gimli/pull/164

**Comment by jonhoo** [comment]
LGTM. Looking through `StateMachine`, it seems to me like the references yielded by `StateMachine::next_row` are actually really `&'input`. Is the reason we don't expose them as such simply that we don't want to use `unsafe`, or is there some deeper dependency I'm not seeing? If `StateMachine` actually just kept references internally (in addition to registers), cloning it would be *much* cheaper.

Alternatively, in `addr2line`, could I (just to try it) re-use the references yielded by `StateMachine::next_row` after that `StateMachine` has been dropped (or has just moved on)? If so, it would be pretty simple to approximate the solution we discussed with storing `(addr, offset)`.

**Comment by philipc** [comment]
binutils addr2info caches all the line rows and does a binary search too.

> Looking through StateMachine, it seems to me like the references yielded by StateMachine::next_row are actually really &'input.

`StateMachine::next_row` returns references to fields in `StateMachine`, so the lifetime of those references is not `'input`. The values of the fields do only contain references that have a lifetime of `'input`, but that would only be relevant if we returned copies of those values, instead of references to them.

> If StateMachine actually just kept references internally (in addition to registers), cloning it would be much cheaper.

The problem is that `StateMachine` needs to add entries to the list of files in the `LineNumberProgramHeader`. If it only kept a reference to the header internally, then it would need to be a mutable reference, and I think that would prevent you cloning `StateMachine` at all.

> Alternatively, in addr2line, could I (just to try it) re-use the references yielded by StateMachine::next_row after that StateMachine has been dropped (or has just moved on)?

If you use a borrow of something that has been dropped or mutated then you have memory unsafety. Perhaps I misunderstand what you are asking?

**Comment by jonhoo** [comment]
Ah, I didn't realize `StateMachine` had to modify `LineNumberProgramHeader` -- I thought it was a struct overlay of the memory mapped debug data, in which case caching the borrow of it would be safe (since it wouldn't be mutated). Given that it needs to be mutated, that is obviously not the case. Unfortunate..

**Comment by philipc** [comment]
I don't think we use struct overlays of memory mapped data anywhere in gimli, so the zero-copy is a bit of a lie there :) DWARF doesn't tend to allow overlays because it uses variable length encodings. We do use short lived values on the stack or in registers wherever possible though.

**Comment by jonhoo** [comment]
@philipc Mmm, I took the zero-copy too literally. I'm working on a patch to test the binary search idea now, and ran across the fact that there's no way to get the current `LineNumberRow` from a `StateMachine`, only its header. I can work around it, but might be a worthwhile addition (similar to `EntriesCursor::current`).
