### ISSUE TITLE
Doesn't seem to live up to performance claims?

### ISSUE THREAD

**Issue by vlovich** [gimli-rs/addr2line#212]
I have a large binary (~256 MB before strip, 209 MB total) & I did a simple comparison, calling addr2line in a loop 20 times (providing 16 addresses from a real call stack) & comparing peak RSS & the total time taken. The command line invoked was
`<addr2line exe> --pretty-print -C -f -i  --exe <path to exe> <addresses>` (all output was piped to `/dev/null`).

The results are:
binutils: ~4s, 236 MB RSS
this crate: ~3s, 384 MB RSS
llvm-symbolizer: ~3s 138 MB RSS
elfutils: ~1s 53 MB RSS

I did notice that elfutils for some reason didn't manage to report the location of the function nor the function arguments so it's possible there's some bug or other issue with elfutils invalidating that result.

Regardless, it looks like llvm-symbolizer does use almost 1/3 the RAM for the same runtime performance & even binutils uses less RAM (albeit @ 33% slower runtime).

**Comment by philipc** [comment]
It's possible we need to do some benchmarks and performance improvements for larger binaries. Also, most performance work so far has been on time, rather than memory.

Did some rough tests here, using 20 addresses each 16KB apart, only 1 invocation each.

~50 MB libUE4Editor-Core.so:
binutils: 0.17s, 90 MB RSS
this crate: 0.06s, 76 MB RSS
llvm-addr2line: 0.11s, 60 MB RSS
eu-addr2line: 0.02s, 7.5 MB RSS (incomplete results)

~470MB libxul.debug:
binutils: 4.79s, 1.3 GB RSS
this crate: 8.18s, 2.6 GB RSS
llvm-addr2line: 6.03s 2.4 GB RSS
elfutils: 5.92s 2.2 GB RSS

Also, versions might matter:
binutils: 2.34
llvm: 10
elfutils: 0.176

So yeah, there's room for improvement.

**Comment by vlovich** [comment]
I did this test on:

binutils 2.36.1
elfutils: 0.183
llvm 11.1.
Just ran llvm-13 & saw it drop RSS usage further to ~110 mb of RAM.

**Comment by vlovich** [comment]
I just used heaptrack to do a preliminary analysis. Most of the memory comes from the sections loaded in `addr2line::Context::new`. Is it possible that the "lazy" property of Gimli isn't being inherited (or there's suboptimal behavior in it?). The addr2line reference implementation in `Context::new` is parsing all sections even if they're not actually needed? It seems to actually copy all of the sections into the heap instead of copying it as-needed when iterating? Additionally, is it not a bit weird that the sections are getting dereferenced into RAM even though it's coming from mmap regions?

**Comment by philipc** [comment]
Yeah, `Context::new` copies the input sections (this is documented). I forgot that the `addr2line` example uses this too.

**Comment by vlovich** [comment]
How can I avoid copying the sections? I saw the note in the documentation but the details are unclear as to how to avoid the input data copies (& no examples to that effect either). Do I use EndianSlice or EndianRcSlice?. Similarly, there's the following note:
```
  92     /// Performance sensitive applications may want to use `Context::from_dwarf`
  93     /// with a more specialised `gimli::Reader` implementation.
```

& it's unclear how one would outperform the default readers (similarly it's unclear if the performance implications are around memory usage & the provided EndianXSlice variants all make copies & one always needs a custom reader to avoid those copies).

**Comment by philipc** [comment]
`EndianArcSlice` is similar to `EndianRcSlice`, but its reference counting is slower. In hindsight, using either of these readers is generally not a good idea. They make things simple, but they're not ideal behaviour.

`EndianSlice` is good for performance, but the lifetime makes it more awkward to manage. Additionally, we still need to somehow handle the case where the section is compressed, and so an allocation somewhere may be required.

I think we should do the same thing as the [`dwarfdump` example in `gimli`](https://github.com/gimli-rs/gimli/blob/00f4ee6a288d2e7f02b6841a5949d839e99d8359/examples/dwarfdump.rs#L605), which uses `EndianSlice` with an arena for the allocation if required. `dwarfdump` is a bit more complicated because it also handles relocations, which I don't think we need here, but otherwise that might be a good enough for you to follow?

**Comment by vlovich** [comment]
Sounds good! Yeah, I think having an interface that where you give it an arena & it returns an EndianSlice is a good API for those that need performance (hopefully the lifetime awkwardness could be contained). That way the addr2line & dwarfdump implementations can shrink in size.

I'm excited to see what kind of memory savings (& presumably runtime since we'd be doing fewer copies) we can realize.
