### ISSUE TITLE
Ability to shrink the library?

### ISSUE THREAD

**Issue by vlovich** [gimli-rs/addr2line#214]
Our use-case doesn't have us processing anything but ELF files. I'm not familiar enough with cargo but I don't think as a consumer of the addr2line API I can restrict the features of crates that are depended on. Does this mean I would need to add a feature that only depended on a subset of the `object` crate's file formats? Maybe makes sense to reexport those features?

**Comment by philipc** [comment]
I suggest you don't use the `object` feature of this crate at all (and you don't need it if you're already using `Context::from_dwarf*`).

**Comment by vlovich** [comment]
We don't but I still see WASM library being built, so even if Rust is able to elide it from the resultant binary, it would cut down on our build time a bit.

**Comment by philipc** [comment]
Yes, you still need to use `object`, but you can disable the `object` dependency for this crate, and specify `object` in your `Cargo.toml` with whatever features you want (exclude wasm from those features).

As an alternative, if you did need to use `Context::new`, we could look at disabling all nonessential `object` features in this crate's `Cargo.toml`. I don't think we ever want to reexport features though, since users can always add to the features via their own `Cargo.toml`.

**Comment by philipc** [comment]
I think your question has been answered. Also, the latest `object` release disables wasm by default.
