### ISSUE TITLE
Assumption of monotonically increasing addresses in line number programs is wrong

### ISSUE THREAD

**Issue by khuey** [gimli-rs/addr2line#29]
in practice, not just in theory.  See https://gist.github.com/khuey/5b0a7d0cc68360e85cd31c67b0c0b0e7.

**Comment by philipc** [comment]
@khuey Did you end up using the sequences API that was added to gimli? I looked at changing addr2line to use it, but it turned out much slower than I had hoped, because some sequences can be very long.

So I'm now thinking that we need to keep the existing skiplist but:
- force a skiplist entry at the start of sequences in addition to every nth row
- fully populate and sort the skiplist, instead of lazily reading rows

It'll require more memory than only caching the start of sequences, but I don't have any better ideas.

**Comment by khuey** [comment]
I am using it.  Performance hasn't been a big concern for us but I haven't tried it on something insane like the single-file sqlite.c.

**Comment by philipc** [comment]
Yet another approach is to just cache every row. This has the advantage of being faster at the cost of more memory. We don't need to cache the full row though. This is also what every other library I've looked at does (including libbacktrace). I have nearly completed implementation of this approach (see https://github.com/philipc/addr2line/commit/aa56a3a42f8318b15a63cbec425f9aa0f4c68cc9).
