### ISSUE TITLE
Support reading in object files for executables on macOS

### ISSUE THREAD

**Issue by jrmuizel** [gimli-rs/addr2line#87]
By default, the linker doesn't include debug info into the resulting executable. It's either left in the .o files or put in a dsym file. In the situation where it's left in the .o files there are OSO stabs entries that give the paths of the .o files. We should read those in as needed to resolve the addresses.

**Comment by jrmuizel** [comment]
There's some code to do this at https://github.com/mstange/profiler-dwarf-lookup

**Comment by philipc** [comment]
Do you think it makes sense to add something to the object crate that performs the task of `Resolver` in that code? I'd probably make it return `Vec<(file_name, Vec<Symbol>)>` (or a similar iterator) and let the caller figure out which symbols contain the addresses they want.

**Comment by jrmuizel** [comment]
@mstange

**Comment by philipc** [comment]
@mstange I noticed a couple of differences in how LLVM parses the symbol entries in [MachODebugMapParser](https://github.com/llvm-mirror/llvm/blob/52c132f528d9a2325771f46304468c2677ba06c8/tools/dsymutil/MachODebugMapParser.cpp#L358):

- It uses `N_FUN` with null names to terminate functions, instead of waiting for the next `N_FUN` with a name. It looks like using the terminating `N_FUN` is better because it gives the function size.
- It doesn't handle `N_SO`. Did you encounter a case where the `N_SO` handling is required?

**Comment by mstange** [comment]
Oh, the terminating `N_FUN` comes with the size! I didn't realize that, that's great!

I did not encounter a case where `N_SO` handling is required. I think all `N_FUN` symbols are always between an `N_OSO` and a terminating `N_SO`, so we might as well treat the `N_OSO` as the separator and ignore the section terminator.

One important thing that the current `profiler-dwarf-lookup` code doesn't handle is OSOs that point to archive files: For example, you can have an OSO symbol with the string `/Users/mstange/code/obj-m-opt/toolkit/library/../../js/src/build/libjs_static.a(JSAtom.o)`. Then you need to load `libjs_static.a` as a [`goblin::archive::Archive`](https://docs.rs/goblin/0.0.15/goblin/archive/struct.Archive.html) and extract the member with the name `/Users/mstange/code/obj-m-opt/toolkit/library/../../js/src/build/libjs_static.a(JSAtom.o)`. This probably requires a change to your proposed API in order to be represented properly.

**Comment by philipc** [comment]
> It's either left in the .o files or put in a dsym file. In the situation where it's left in the .o files there are OSO stabs entries that give the paths of the .o files. 

I don't know much about macOS, but it appears that the OSO entries are what dsymutil uses. Can you run dsymutil to get a dsym and use that instead? Using the .o files seems like a niche use case.

**Comment by jrmuizel** [comment]
Running dsymutil is pretty time consuming (see https://github.com/rust-lang/rust/issues/47240) so it's nice to avoid it if at all possible. Further, most tools (lldb, gdb, nm, Instruments, ...) on macOS support using the OSO entries directly without needed a dsym file.

**Comment by philipc** [comment]
My current thinking is to change `object::SymbolMap` to also include the object file name. I've done some work to start on that [here](https://github.com/philipc/object/commit/1dca75176e57913c21f5ad8eca392b077e881375), but it might be a while before I get to do the corresponding addr2line changes.

**Comment by luser** [comment]
This got a fully-fleshed-out implementation in the `fix-stacks` binary:
https://github.com/mozilla/fix-stacks/blob/c30daaef43bd15486fba189b06487aa24dad3492/src/main.rs#L433-L502

**Comment by mstange** [comment]
`object` now exposes these references in [`Object::object_map`](https://docs.rs/object/0.26.2/object/read/trait.Object.html#method.object_map). That's what I use in profiler-get-symbols: https://github.com/mstange/profiler-get-symbols/blob/3c315ba523e2c876e3de493ba36ef9fc0d01affa/lib/src/macho.rs#L317-L319

**Comment by philipc** [comment]
backtrace-rs implemented this in https://github.com/rust-lang/backtrace-rs/pull/377. This needs to be handled at a higher level than the `addr2line` API, so closing this issue.

**Comment by mstange** [comment]
@jrmuizel Did you file this issue about the addr2line crate API or about the addr2line CLI example in this repo?

**Comment by philipc** [comment]
Ah sure, that probably isn't too hard to do (rough version at https://github.com/philipc/addr2line/commit/65f215492371a153b211e59959239061bdfbd376). I don't currently have a macOS system to develop on though.

**Comment by philipc** [comment]
I think https://github.com/mstange/samply/tree/main/wholesym-addr2line supports this, so hoping that is sufficient now.
